// Reference catalog of common construction materials in Argentina (Córdoba).
// Providers apply their own price factor, availability and URL scheme on top of
// this so each supplier stays fully independent. Prices are indicative ARS
// reference values used as fallback when live scraping is unavailable.

export interface CatalogItem {
  sku: string;
  title: string;
  brand: string;
  category: string;
  unit: string;
  packageSize: string;
  basePrice: number; // ARS reference
  keywords: string[];
  image: string;
}

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=600&q=70`;

export const CATALOG: CatalogItem[] = [
  {
    sku: "cemento-loma-negra-50",
    title: "Cemento Portland Loma Negra CPC40 x 50 kg",
    brand: "Loma Negra",
    category: "Cemento y cal",
    unit: "bolsa",
    packageSize: "50 kg",
    basePrice: 11800,
    keywords: ["cemento", "portland", "loma negra", "cpc"],
    image: img("photo-1607400201889-565b1ee75f8e"),
  },
  {
    sku: "cemento-holcim-50",
    title: "Cemento Holcim Plus x 50 kg",
    brand: "Holcim",
    category: "Cemento y cal",
    unit: "bolsa",
    packageSize: "50 kg",
    basePrice: 11200,
    keywords: ["cemento", "holcim", "portland"],
    image: img("photo-1607400201889-565b1ee75f8e"),
  },
  {
    sku: "cal-hidraulica-milagro-25",
    title: "Cal Hidráulica Milagro x 25 kg",
    brand: "Milagro",
    category: "Cemento y cal",
    unit: "bolsa",
    packageSize: "25 kg",
    basePrice: 6400,
    keywords: ["cal", "hidraulica", "milagro"],
    image: img("photo-1581092160562-40aa08e78837"),
  },
  {
    sku: "cal-plastificada-cacique-30",
    title: "Cal Plastificada Cacique x 30 kg",
    brand: "Cacique",
    category: "Cemento y cal",
    unit: "bolsa",
    packageSize: "30 kg",
    basePrice: 7200,
    keywords: ["cal", "plastificada", "cacique", "hidrat"],
    image: img("photo-1581092160562-40aa08e78837"),
  },
  {
    sku: "ladrillo-hueco-12x18x33",
    title: "Ladrillo Hueco Cerámico 12x18x33",
    brand: "Cerámica Quilmes",
    category: "Ladrillos y bloques",
    unit: "unidad",
    packageSize: "12x18x33 cm",
    basePrice: 720,
    keywords: ["ladrillo", "hueco", "ceramico", "12x18x33"],
    image: img("photo-1516216628859-9bccecab13ca"),
  },
  {
    sku: "ladrillo-comun-macizo",
    title: "Ladrillo Común Macizo",
    brand: "Genérico",
    category: "Ladrillos y bloques",
    unit: "unidad",
    packageSize: "5x11x24 cm",
    basePrice: 165,
    keywords: ["ladrillo", "comun", "macizo"],
    image: img("photo-1516216628859-9bccecab13ca"),
  },
  {
    sku: "bloque-hormigon-19x19x39",
    title: "Bloque de Hormigón 19x19x39",
    brand: "Blokret",
    category: "Ladrillos y bloques",
    unit: "unidad",
    packageSize: "19x19x39 cm",
    basePrice: 980,
    keywords: ["bloque", "hormigon", "19x19x39"],
    image: img("photo-1607400201889-565b1ee75f8e"),
  },
  {
    sku: "arena-fina-m3",
    title: "Arena Fina Lavada x m³",
    brand: "Áridos Córdoba",
    category: "Áridos",
    unit: "m³",
    packageSize: "1 m³",
    basePrice: 34000,
    keywords: ["arena", "fina", "lavada", "arido"],
    image: img("photo-1518709268805-4e9042af9f23"),
  },
  {
    sku: "piedra-partida-6-20",
    title: "Piedra Partida 6-20 x m³",
    brand: "Áridos Córdoba",
    category: "Áridos",
    unit: "m³",
    packageSize: "1 m³",
    basePrice: 41000,
    keywords: ["piedra", "partida", "arido", "grava"],
    image: img("photo-1518709268805-4e9042af9f23"),
  },
  {
    sku: "hierro-aletado-8mm",
    title: "Hierro Aletado Ø8 mm x 12 m",
    brand: "Acindar",
    category: "Hierro y acero",
    unit: "barra",
    packageSize: "8 mm x 12 m",
    basePrice: 9700,
    keywords: ["hierro", "aletado", "acindar", "8mm", "varilla"],
    image: img("photo-1504307651254-35680f356dfd"),
  },
  {
    sku: "hierro-aletado-10mm",
    title: "Hierro Aletado Ø10 mm x 12 m",
    brand: "Acindar",
    category: "Hierro y acero",
    unit: "barra",
    packageSize: "10 mm x 12 m",
    basePrice: 15200,
    keywords: ["hierro", "aletado", "acindar", "10mm", "varilla"],
    image: img("photo-1504307651254-35680f356dfd"),
  },
  {
    sku: "malla-sima-15x15",
    title: "Malla Sima Q188 15x15 x 6x2,15 m",
    brand: "Acindar",
    category: "Hierro y acero",
    unit: "panel",
    packageSize: "6 x 2,15 m",
    basePrice: 62000,
    keywords: ["malla", "sima", "q188", "acindar"],
    image: img("photo-1504307651254-35680f356dfd"),
  },
  {
    sku: "membrana-40-10m",
    title: "Membrana Asfáltica 40 kg Aluminio x 10 m",
    brand: "Megaflex",
    category: "Aislaciones",
    unit: "rollo",
    packageSize: "10 m x 1 m",
    basePrice: 58000,
    keywords: ["membrana", "asfaltica", "megaflex", "aluminio"],
    image: img("photo-1503387762-592deb58ef4e"),
  },
  {
    sku: "hidrofugo-ceresita-4l",
    title: "Hidrófugo Ceresita x 4 L",
    brand: "Sika",
    category: "Impermeabilizantes",
    unit: "bidón",
    packageSize: "4 L",
    basePrice: 14500,
    keywords: ["hidrofugo", "ceresita", "sika", "impermeable"],
    image: img("photo-1580901368919-7738efb0f87e"),
  },
  {
    sku: "pintura-latex-interior-20l",
    title: "Látex Interior Mate Blanco x 20 L",
    brand: "Alba",
    category: "Pinturas",
    unit: "balde",
    packageSize: "20 L",
    basePrice: 46000,
    keywords: ["pintura", "latex", "interior", "alba", "blanco"],
    image: img("photo-1562259949-e8e7689d7828"),
  },
  {
    sku: "pintura-latex-exterior-20l",
    title: "Látex Exterior Frentes x 20 L",
    brand: "Tersuave",
    category: "Pinturas",
    unit: "balde",
    packageSize: "20 L",
    basePrice: 58500,
    keywords: ["pintura", "latex", "exterior", "tersuave", "frente"],
    image: img("photo-1562259949-e8e7689d7828"),
  },
  {
    sku: "porcelanato-60x60-pulido",
    title: "Porcelanato Pulido 60x60 Blanco x m²",
    brand: "Ilva",
    category: "Pisos y revestimientos",
    unit: "m²",
    packageSize: "60x60 cm",
    basePrice: 18900,
    keywords: ["porcelanato", "pulido", "60x60", "ilva", "piso"],
    image: img("photo-1600607687939-ce8a6c25118c"),
  },
  {
    sku: "ceramica-esmaltada-36x36",
    title: "Cerámica Esmaltada 36x36 x m²",
    brand: "Cerro Negro",
    category: "Pisos y revestimientos",
    unit: "m²",
    packageSize: "36x36 cm",
    basePrice: 9800,
    keywords: ["ceramica", "esmaltada", "36x36", "cerro negro", "piso"],
    image: img("photo-1600607687939-ce8a6c25118c"),
  },
  {
    sku: "adhesivo-klaukol-30kg",
    title: "Adhesivo Klaukol Impermeable x 30 kg",
    brand: "Klaukol",
    category: "Pisos y revestimientos",
    unit: "bolsa",
    packageSize: "30 kg",
    basePrice: 12800,
    keywords: ["adhesivo", "klaukol", "pegamento", "ceramica"],
    image: img("photo-1581092160562-40aa08e78837"),
  },
  {
    sku: "placa-yeso-durlock-12mm",
    title: "Placa de Yeso Durlock 12,5 mm 1,20x2,40",
    brand: "Durlock",
    category: "Construcción en seco",
    unit: "placa",
    packageSize: "1,20 x 2,40 m",
    basePrice: 17500,
    keywords: ["placa", "yeso", "durlock", "12mm", "roca"],
    image: img("photo-1503387762-592deb58ef4e"),
  },
  {
    sku: "perfil-montante-70",
    title: "Perfil Montante 70 mm x 2,60 m",
    brand: "Durlock",
    category: "Construcción en seco",
    unit: "perfil",
    packageSize: "70 mm x 2,60 m",
    basePrice: 6300,
    keywords: ["perfil", "montante", "70", "durlock", "steel"],
    image: img("photo-1504307651254-35680f356dfd"),
  },
  {
    sku: "chapa-sinusoidal-c25",
    title: "Chapa Sinusoidal C25 Galvanizada x m",
    brand: "Ternium",
    category: "Techos",
    unit: "m",
    packageSize: "1,10 m ancho",
    basePrice: 10600,
    keywords: ["chapa", "sinusoidal", "galvanizada", "ternium", "techo"],
    image: img("photo-1503387762-592deb58ef4e"),
  },
  {
    sku: "aislante-doble-alu-10mm",
    title: "Aislante Térmico Doble Aluminio 10 mm x m²",
    brand: "Isolant",
    category: "Aislaciones",
    unit: "m²",
    packageSize: "rollo 1,20 m",
    basePrice: 4200,
    keywords: ["aislante", "termico", "isolant", "aluminio"],
    image: img("photo-1503387762-592deb58ef4e"),
  },
  {
    sku: "yeso-proyectable-30kg",
    title: "Yeso Tuni Proyectable x 30 kg",
    brand: "Tuni",
    category: "Revoques",
    unit: "bolsa",
    packageSize: "30 kg",
    basePrice: 8600,
    keywords: ["yeso", "tuni", "proyectable", "revoque"],
    image: img("photo-1581092160562-40aa08e78837"),
  },
];
